services:

  api:
    image: tasker:latest
    volumes:
      - ./conf:/app/conf
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8000:8000"
    command: python -m app.main
    restart: always


  worker:
    image: tasker:latest
    environment:
      DOCKER_REGISTRIES: 192.168.31.98:5000
      DOCKER_USERNAME: admin
      DOCKER_PASSWORD: xiaofengfeng
    volumes:
      - ./conf:/app/conf
      - /var/run/docker.sock:/var/run/docker.sock
    command: celery -A app.tasks worker --loglevel=info --pool=solo --concurrency=1
    restart: always

#  flower:
#    image: mher/flower
#    ports:
#      - "5555:5555"
#    environment:
#      - CELERY_BROKER_URL=redis://redis:6379/0
#    depends_on:
#      - redis